volumes:
  txty-database:
    name: txty-database
    external: true
  txty-assets:
    name: txty-assets
    external: true
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - txty-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: chrztoph/texterify:${TXTY_TAG}
    env_file:
      - secrets.env
      - .env
    depends_on:
      - db
    volumes:
      - txty-assets:/var/www/app/storage
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        BUILDER_IMAGE: chrztoph/texterify:${TXTY_TAG}
    depends_on:
      - app
    ports:
      - 80:80
  sidekiq:
    image: chrztoph/texterify:${TXTY_TAG}
    env_file:
      - secrets.env
      - .env
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
    volumes:
      - txty-assets:/var/www/app/storage
  redis:
    image: redis:6.2.0-alpine
